;;; test-hog.el -*- lexical-binding: t; -*-

(require 'verilog-port-copy)
(require 'ert)

(add-to-list 'treesit-extra-load-path "~/.emacs.d/.local/etc/tree-sitter")
(add-to-list 'treesit-extra-load-path "~/.emacs.d/.local/cache/tree-sitter")

(defmacro completion-test (file port-list)
  `(ert-deftest ,(intern file) nil
     (should (equal
              ,port-list
              (progn (find-file (concat (locate-dominating-file "." ".git") ,file))
                     (goto-char (point-min))
                     (verilog-ts--collect-candidates))))))

(completion-test "test/test1.sv"
                 '(#("clk" 0 3 (verilog-ts-type "port"))
                   #("din" 0 3 (verilog-ts-type "port"))
                   #("sum" 0 3 (verilog-ts-type "port"))
                   #("sum_a" 0 5 (verilog-ts-type "logic"))
                   #("sum_b" 0 5 (verilog-ts-type "logic"))
                   #("din_a" 0 5 (verilog-ts-type "logic"))
                   #("din_b" 0 5 (verilog-ts-type "logic"))
                   #("din_padded" 0 10 (verilog-ts-type "logic"))
                   #("N" 0 1 (verilog-ts-type "parameter"))
                   #("W" 0 1 (verilog-ts-type "parameter"))
                   #("NPOW2" 0 5 (verilog-ts-type "localparam"))
                   #("NB" 0 2 (verilog-ts-type "localparam"))
                   #("module" 0 6 (verilog-ts-type "keyword"))
                   #("endmodule" 0 9 (verilog-ts-type "keyword"))
                   #("interface" 0 9 (verilog-ts-type "keyword"))
                   #("endinterface" 0 12 (verilog-ts-type "keyword"))
                   #("package" 0 7 (verilog-ts-type "keyword"))
                   #("endpackage" 0 10 (verilog-ts-type "keyword"))
                   #("program" 0 7 (verilog-ts-type "keyword"))
                   #("endprogram" 0 10 (verilog-ts-type "keyword"))
                   #("class" 0 5 (verilog-ts-type "keyword"))
                   #("endclass" 0 8 (verilog-ts-type "keyword"))
                   #("primitive" 0 9 (verilog-ts-type "keyword"))
                   #("endprimitive" 0 12 (verilog-ts-type "keyword"))
                   #("checker" 0 7 (verilog-ts-type "keyword"))
                   #("endchecker" 0 10 (verilog-ts-type "keyword"))
                   #("config" 0 6 (verilog-ts-type "keyword"))
                   #("endconfig" 0 9 (verilog-ts-type "keyword"))
                   #("input" 0 5 (verilog-ts-type "keyword"))
                   #("output" 0 6 (verilog-ts-type "keyword"))
                   #("inout" 0 5 (verilog-ts-type "keyword"))
                   #("ref" 0 3 (verilog-ts-type "keyword"))
                   #("wire" 0 4 (verilog-ts-type "keyword"))
                   #("tri" 0 3 (verilog-ts-type "keyword"))
                   #("wand" 0 4 (verilog-ts-type "keyword"))
                   #("wor" 0 3 (verilog-ts-type "keyword"))
                   #("trior" 0 5 (verilog-ts-type "keyword"))
                   #("triand" 0 6 (verilog-ts-type "keyword"))
                   #("tri0" 0 4 (verilog-ts-type "keyword"))
                   #("tri1" 0 4 (verilog-ts-type "keyword"))
                   #("trireg" 0 6 (verilog-ts-type "keyword"))
                   #("uwire" 0 5 (verilog-ts-type "keyword"))
                   #("supply0" 0 7 (verilog-ts-type "keyword"))
                   #("supply1" 0 7 (verilog-ts-type "keyword"))
                   #("reg" 0 3 (verilog-ts-type "keyword"))
                   #("logic" 0 5 (verilog-ts-type "keyword"))
                   #("bit" 0 3 (verilog-ts-type "keyword"))
                   #("byte" 0 4 (verilog-ts-type "keyword"))
                   #("shortint" 0 8 (verilog-ts-type "keyword"))
                   #("int" 0 3 (verilog-ts-type "keyword"))
                   #("longint" 0 7 (verilog-ts-type "keyword"))
                   #("integer" 0 7 (verilog-ts-type "keyword"))
                   #("time" 0 4 (verilog-ts-type "keyword"))
                   #("real" 0 4 (verilog-ts-type "keyword"))
                   #("shortreal" 0 9 (verilog-ts-type "keyword"))
                   #("realtime" 0 8 (verilog-ts-type "keyword"))
                   #("signed" 0 6 (verilog-ts-type "keyword"))
                   #("unsigned" 0 8 (verilog-ts-type "keyword"))
                   #("void" 0 4 (verilog-ts-type "keyword"))
                   #("parameter" 0 9 (verilog-ts-type "keyword"))
                   #("localparam" 0 10 (verilog-ts-type "keyword"))
                   #("genvar" 0 6 (verilog-ts-type "keyword"))
                   #("specparam" 0 9 (verilog-ts-type "keyword"))
                   #("automatic" 0 9 (verilog-ts-type "keyword"))
                   #("static" 0 6 (verilog-ts-type "keyword"))
                   #("local" 0 5 (verilog-ts-type "keyword"))
                   #("protected" 0 9 (verilog-ts-type "keyword"))
                   #("virtual" 0 7 (verilog-ts-type "keyword"))
                   #("pure" 0 4 (verilog-ts-type "keyword"))
                   #("extern" 0 6 (verilog-ts-type "keyword"))
                   #("const" 0 5 (verilog-ts-type "keyword"))
                   #("var" 0 3 (verilog-ts-type "keyword"))
                   #("typedef" 0 7 (verilog-ts-type "keyword"))
                   #("enum" 0 4 (verilog-ts-type "keyword"))
                   #("struct" 0 6 (verilog-ts-type "keyword"))
                   #("union" 0 5 (verilog-ts-type "keyword"))
                   #("packed" 0 6 (verilog-ts-type "keyword"))
                   #("tagged" 0 6 (verilog-ts-type "keyword"))
                   #("always" 0 6 (verilog-ts-type "keyword"))
                   #("always_ff" 0 9 (verilog-ts-type "keyword"))
                   #("always_comb" 0 11 (verilog-ts-type "keyword"))
                   #("always_latch" 0 12 (verilog-ts-type "keyword"))
                   #("initial" 0 7 (verilog-ts-type "keyword"))
                   #("final" 0 5 (verilog-ts-type "keyword"))
                   #("begin" 0 5 (verilog-ts-type "keyword"))
                   #("end" 0 3 (verilog-ts-type "keyword"))
                   #("fork" 0 4 (verilog-ts-type "keyword"))
                   #("join" 0 4 (verilog-ts-type "keyword"))
                   #("join_any" 0 8 (verilog-ts-type "keyword"))
                   #("join_none" 0 9 (verilog-ts-type "keyword"))
                   #("function" 0 8 (verilog-ts-type "keyword"))
                   #("endfunction" 0 11 (verilog-ts-type "keyword"))
                   #("task" 0 4 (verilog-ts-type "keyword"))
                   #("endtask" 0 7 (verilog-ts-type "keyword"))
                   #("return" 0 6 (verilog-ts-type "keyword"))
                   #("generate" 0 8 (verilog-ts-type "keyword"))
                   #("endgenerate" 0 11 (verilog-ts-type "keyword"))
                   #("if" 0 2 (verilog-ts-type "keyword"))
                   #("else" 0 4 (verilog-ts-type "keyword"))
                   #("case" 0 4 (verilog-ts-type "keyword"))
                   #("casex" 0 5 (verilog-ts-type "keyword"))
                   #("casez" 0 5 (verilog-ts-type "keyword"))
                   #("endcase" 0 7 (verilog-ts-type "keyword"))
                   #("for" 0 3 (verilog-ts-type "keyword"))
                   #("foreach" 0 7 (verilog-ts-type "keyword"))
                   #("while" 0 5 (verilog-ts-type "keyword"))
                   #("do" 0 2 (verilog-ts-type "keyword"))
                   #("repeat" 0 6 (verilog-ts-type "keyword"))
                   #("forever" 0 7 (verilog-ts-type "keyword"))
                   #("break" 0 5 (verilog-ts-type "keyword"))
                   #("continue" 0 8 (verilog-ts-type "keyword"))
                   #("unique" 0 6 (verilog-ts-type "keyword"))
                   #("unique0" 0 7 (verilog-ts-type "keyword"))
                   #("priority" 0 8 (verilog-ts-type "keyword"))
                   #("default" 0 7 (verilog-ts-type "keyword"))
                   #("assign" 0 6 (verilog-ts-type "keyword"))
                   #("force" 0 5 (verilog-ts-type "keyword"))
                   #("release" 0 7 (verilog-ts-type "keyword"))
                   #("deassign" 0 8 (verilog-ts-type "keyword"))
                   #("posedge" 0 7 (verilog-ts-type "keyword"))
                   #("negedge" 0 7 (verilog-ts-type "keyword"))
                   #("edge" 0 4 (verilog-ts-type "keyword"))
                   #("this" 0 4 (verilog-ts-type "keyword"))
                   #("super" 0 5 (verilog-ts-type "keyword"))
                   #("new" 0 3 (verilog-ts-type "keyword"))
                   #("null" 0 4 (verilog-ts-type "keyword"))
                   #("extends" 0 7 (verilog-ts-type "keyword"))
                   #("implements" 0 10 (verilog-ts-type "keyword"))
                   #("import" 0 6 (verilog-ts-type "keyword"))
                   #("export" 0 6 (verilog-ts-type "keyword"))
                   #("with" 0 4 (verilog-ts-type "keyword"))
                   #("assert" 0 6 (verilog-ts-type "keyword"))
                   #("assume" 0 6 (verilog-ts-type "keyword"))
                   #("cover" 0 5 (verilog-ts-type "keyword"))
                   #("restrict" 0 8 (verilog-ts-type "keyword"))
                   #("property" 0 8 (verilog-ts-type "keyword"))
                   #("endproperty" 0 11 (verilog-ts-type "keyword"))
                   #("sequence" 0 8 (verilog-ts-type "keyword"))
                   #("endsequence" 0 11 (verilog-ts-type "keyword"))
                   #("disable" 0 7 (verilog-ts-type "keyword"))
                   #("iff" 0 3 (verilog-ts-type "keyword"))
                   #("clocking" 0 8 (verilog-ts-type "keyword"))
                   #("endclocking" 0 11 (verilog-ts-type "keyword"))
                   #("covergroup" 0 10 (verilog-ts-type "keyword"))
                   #("endgroup" 0 8 (verilog-ts-type "keyword"))
                   #("coverpoint" 0 10 (verilog-ts-type "keyword"))
                   #("cross" 0 5 (verilog-ts-type "keyword"))
                   #("wait" 0 4 (verilog-ts-type "keyword"))
                   #("event" 0 5 (verilog-ts-type "keyword"))
                   #("specify" 0 7 (verilog-ts-type "keyword"))
                   #("endspecify" 0 10 (verilog-ts-type "keyword"))
                   #("table" 0 5 (verilog-ts-type "keyword"))
                   #("endtable" 0 8 (verilog-ts-type "keyword"))
                   #("macromodule" 0 11 (verilog-ts-type "keyword"))
                   #("connectmodule" 0 13 (verilog-ts-type "keyword"))
                   #("endconnectmodule" 0 16 (verilog-ts-type "keyword"))
                   #("bind" 0 4 (verilog-ts-type "keyword"))))
